In [31]:
import numpy as np
import pandas as pd

In [32]:
dataset = pd.read_csv('classification_data/Social_Network_Ads.csv').values
print(dataset)

[[   19 19000     0]
 [   35 20000     0]
 [   26 43000     0]
 ...
 [   50 20000     1]
 [   36 33000     0]
 [   49 36000     1]]


In [33]:
X = dataset[:,:-1]
y = dataset[:,-1]

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=5)

In [35]:
# Scaling
# ※ 일반적인 Logistic regression은 이론적으로 scaling이 필요 없으나
#    sklearn의 logistic regression은 linear regression의 개선된 모델이 적용되어
#    scaling된 데이터에 대해서 좋은 결과를 보여준다.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
print(X_train)
print(X_train_sc)

[[    46  23000]
 [    28  44000]
 [    51  23000]
 [    39 106000]
 [    35  50000]
 [    26  86000]
 [    27  84000]
 [    26  80000]
 [    54 108000]
 [    28  59000]
 [    59  42000]
 [    39  42000]
 [    59  88000]
 [    47  51000]
 [    35  73000]
 [    29  75000]
 [    41  60000]
 [    35  60000]
 [    42 149000]
 [    56 133000]
 [    40  61000]
 [    49  28000]
 [    36  50000]
 [    53  82000]
 [    35  22000]
 [    48  33000]
 [    57  60000]
 [    35  88000]
 [    26  15000]
 [    23  20000]
 [    37  52000]
 [    25  79000]
 [    36 126000]
 [    48  35000]
 [    29  80000]
 [    22  18000]
 [    56  60000]
 [    48 141000]
 [    32 117000]
 [    54  70000]
 [    27  31000]
 [    38  50000]
 [    47  20000]
 [    52 150000]
 [    30  62000]
 [    25  87000]
 [    18  44000]
 [    46  82000]
 [    26  52000]
 [    45  26000]
 [    23  82000]
 [    44 139000]
 [    47  23000]
 [    35  25000]
 [    22  63000]
 [    26  35000]
 [    19  76000]
 [    38  55000]
 [    32  8600

### Logistic regression

In [36]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X_train_sc,y_train)

LogisticRegression()

In [37]:
X_test_sc = sc.transform(X_test)
y_pred_sc = logistic.predict(X_test_sc)

In [38]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred_sc)
print(acc)

0.85
