In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
dataset = pd.read_csv('50_startups.csv').values

In [13]:
X = dataset[:,:-2]
y = dataset[:,-1]
print(X.shape, y.shape)

(50, 3) (50,)


In [14]:
# training과 test 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(35, 3) (15, 3) (35,) (15,)


### Polynomial feature로 X 확장

In [15]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
# PolynomialFeatures 객체 생성(이름 선언), 확장할 degree 파라미터 지정
poly.fit(X_train)
# polynomial로 확장하기 위해 필요한 정보 수집
X_train_poly = poly.transform(X_train)
print('변환 전')
print(X_train)
print('변환 후')
print(X_train_poly)

변환 전
[[23640.93 96189.63 148001.11]
 [0.0 116983.8 45173.06]
 [75328.87 144135.98 134050.07]
 [73994.56 122782.75 303319.26]
 [91992.39 135495.07 252664.93]
 [27892.92 84710.77 164470.71]
 [94657.16 145077.58 282574.31]
 [1000.23 124153.04 1903.93]
 [77044.01 99281.34 140574.81]
 [67532.53 105751.03 304768.73]
 [142107.34 91391.77 366168.42]
 [55493.95 103057.49 214634.81]
 [119943.24 156547.42 256512.92]
 [61994.48 115641.28 91131.24]
 [101913.08 110594.11 229160.95]
 [66051.52 182645.56 118148.2]
 [22177.74 154806.14 28334.72]
 [46426.07 157693.92 210797.67]
 [91749.16 114175.79 294919.57]
 [76253.86 113867.3 298664.47]
 [64664.71 139553.16 137962.62]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [0.0 135426.92 0.0]
 [162597.7 151377.59 443898.53]
 [78013.11 121597.55 264346.06]
 [165349.2 136897.8 471784.1]
 [114523.61 122616.84 261776.23]
 [131876.9 99814.71 362861.36]
 [100671.96 91790.61 249744.55]
 [123334.88 108679.17 304981.62]
 [120542.52 148718.95 311613

In [16]:
# polynomial features로 확장한 후, linear regression 적용
from sklearn.linear_model import LinearRegression
poly_lr = LinearRegression()
poly_lr.fit(X_train_poly,y_train)

LinearRegression()

In [17]:
# test data에 대한 예측값
# poly_lr은 PolynomialFeatures로 확장된 X를 이용하여 학습하였기 때문에
# test data도 동일한 형식으로 확장해야 함
X_test_poly = poly.transform(X_test)
# X_test data에 대해서 fit은 다시 수행하지 않음
y_pred = poly_lr.predict(X_test_poly)

In [18]:
y_pred

array([ 126793.69263605,  103422.31586154,   40427.23886859,
         54194.91799651,  175809.95697383,  166318.75166225,
         -4365.86804275,   96038.17051565, -278626.27456731,
         92739.21520892,   85079.31662701,   99913.8089522 ,
        155989.13762111,   16665.52730783,   32492.89622103])