## 1. NumPy

In [1]:
import numpy as np

In [3]:
# ndarray
arr = np.array([1,2,3,4,5])
mat = np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
print(arr)
print(mat)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# dimension 확인: ndim
print(arr.ndim)
print(mat.ndim)
# shape 확인: shape
print(arr.shape)
print(mat.shape)
# shape tuple이 n개의 정수: n 차원
# 2d array의 경우: (a,b) -> a개의 행, b개의 열
# a: 데이터의 수
# b: 하나의 데이터를 구성하는 요소의 수

1
2
(5,)
(2, 4)


In [9]:
# indexing (특정 요소, 특정 행, 특정 열을 지정)
# index:0부터 시작, -1은 마지막 index를 의미함
# mat[a,b] -> a:행 index, b: 열 index
print(mat[1,2])
# index 1인 행(두번째 행), index 2인 열(세번째 열)

# 행의 마지막 index는 1이므로 아래와 동일 
print(mat[-1,2])

7
7


In [14]:
# slicing
# index의 범위 지정
# a:b -> index a부터 index b-1까지
# ex> 2:5 -> index 2부터 index 4까지
mat2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat2)
print(mat2[0:2,1:3])
# index 0부터 1까지의 행, index 1부터 2까지의 열
# a:b에서 a를 생략할 경우, a는 0을 의미(첫 index부터)하고, 
# b를 생략할 경우, 마지막 index까지 포함함
# 그러므로, a와 b를 모두 생략하면, 처음부터 마지막 index 모두를 의미함
print(mat2[:2,1:3])

print(mat2[0:2,1:4])
print(mat2[:2,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2 3]
 [6 7]]
[[2 3 4]
 [6 7 8]]
[[2 3 4]
 [6 7 8]]


In [19]:
# 특정 행과 열의 지정
print(mat2)
# index 2행
# = index 2 행의 전체 열의 값
print(mat2[2,:])
# index 1열
# = index 1 열의 전체 행의 값
print(mat2[:,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 2  6 10]


In [25]:
# mat2[index,index]: 0차원
# mat2[범위,index] 또는 mat[index,범위]: 1차원
# mat2[범위,범위]: 2차원

print(mat2[1,2])
print(mat2[1,2].ndim)
print(mat2[1,2].shape)

print(mat2[1:2,2])
print(mat2[1:2,2].ndim)
print(mat2[1:2,2].shape)

print(mat2[1,2:3])
print(mat2[1,2:3].ndim)
print(mat2[1,2:3].shape)

print(mat2[1:2,2:3])
print(mat2[1:2,2:3].ndim)
print(mat2[1:2,2:3].shape)

7
0
()
[7]
1
(1,)
[7]
1
(1,)
[[7]]
2
(1, 1)


In [29]:
# 1차원 열(행)과 2차원 열(행)
print(mat2)
print(mat2[:,1])
print(mat2[:,1].shape) # 1차원
print(mat2[:,1:2])
print(mat2[:,1:2].shape) # 2차원

print(mat2[1,:])
print(mat2[1,:].shape) # 1차원
print(mat2[1:2,:])
print(mat2[1:2,:].shape) # 2차원

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]
(3,)
[[ 2]
 [ 6]
 [10]]
(3, 1)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
(4,)
[[5 6 7 8]]
(1, 4)


In [40]:
# shape 변환
col = mat2[:,2]
# index 2인 열, 열 index는 범위가 아니므로 1차원 array가 됨
# shape: (3,)
print(col)
print(col.shape)

# col을 2차원 array 3행1열 (3,1)로 변형하고자 함
print(col.reshape(3,1))

# reshape 값을 -1로 지정하면 자동으로 계산되어 변형됨
print(col.reshape(-1,1))

# 1d array를 2d array로 변경할 때
# array.reshape(-1,1) 또는 array.reshape(1,-1)

# 2d array를 1d array로 변경할 때
# array.reshape(-1)
col2 = mat2[:,3:4]
print(col2)
print(col2.shape)
print(col2.reshape(-1))

[ 3  7 11]
(3,)
[[ 3]
 [ 7]
 [11]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]
(3, 1)
[ 4  8 12]


## 2. pandas

In [41]:
import pandas as pd

In [44]:
data = pd.read_csv('sample.csv')
data

Name  Country   Age   Salary Purchased
0     James   France  44.0  72000.0        No
1       Tim    Spain  27.0  48000.0       Yes
2     Sarah  Germany  30.0  54000.0        No
3    Robert    Spain  38.0  61000.0        No
4      Emma  Germany  40.0      NaN       Yes
5  Jennifer   France  35.0  58000.0       Yes
6     Linda    Spain   NaN  52000.0        No
7    Thomas   France  48.0  79000.0       Yes
8       Ben  Germany  50.0  83000.0        No
9  Scarlett   France  37.0  67000.0       Yes

In [49]:
# read_csv를 통해 로드한 데이터 타입은 DataFrame
print(type(data))
print(data.columns)
# DataFrame.columns는 DataFrame의 column 이름을 반환
# read_csv로 로드할 때, 자동으로 첫번째 행은 column 이름으로 간주함
print(data.index)
# DataFrame.index는 DataFrame의 index를 반환
print(data.values)
print(type(data.values))
# DataFrame.values는 DataFrame의 columns과 index를 제외한 value만 반환
# DataFrame.values의 타입은 ndarray

<class 'pandas.core.frame.DataFrame'>
Index(['Name', 'Country', 'Age', 'Salary', 'Purchased'], dtype='object')
RangeIndex(start=0, stop=10, step=1)
[['James' 'France' 44.0 72000.0 'No']
 ['Tim' 'Spain' 27.0 48000.0 'Yes']
 ['Sarah' 'Germany' 30.0 54000.0 'No']
 ['Robert' 'Spain' 38.0 61000.0 'No']
 ['Emma' 'Germany' 40.0 nan 'Yes']
 ['Jennifer' 'France' 35.0 58000.0 'Yes']
 ['Linda' 'Spain' nan 52000.0 'No']
 ['Thomas' 'France' 48.0 79000.0 'Yes']
 ['Ben' 'Germany' 50.0 83000.0 'No']
 ['Scarlett' 'France' 37.0 67000.0 'Yes']]
<class 'numpy.ndarray'>


In [51]:
# machine learning이나 deep learning에서 data는 대부분의 경우
# ndarray를 사용함 (일부 DataFrame을 사용할 수 도 있으나, 내부적으로 ndarray로 변환)
# 그러므로, csv 파일을 로드한 직후, values를 이용하여 value만 ndarray로 가져오면 편함
data = pd.read_csv('sample.csv').values
print(type(data))
print(data.shape)
print(data)

<class 'numpy.ndarray'>
(10, 5)
[['James' 'France' 44.0 72000.0 'No']
 ['Tim' 'Spain' 27.0 48000.0 'Yes']
 ['Sarah' 'Germany' 30.0 54000.0 'No']
 ['Robert' 'Spain' 38.0 61000.0 'No']
 ['Emma' 'Germany' 40.0 nan 'Yes']
 ['Jennifer' 'France' 35.0 58000.0 'Yes']
 ['Linda' 'Spain' nan 52000.0 'No']
 ['Thomas' 'France' 48.0 79000.0 'Yes']
 ['Ben' 'Germany' 50.0 83000.0 'No']
 ['Scarlett' 'France' 37.0 67000.0 'Yes']]


In [53]:
# 첫번째 열부터 네번째 열까지를 X, 마지막 열을 y로 분리하여 추출 (전체 행)
data = pd.read_csv('sample.csv').values
X = data[:,0:4]
y = data[:,4]
print(X)
print(y)

[['James' 'France' 44.0 72000.0]
 ['Tim' 'Spain' 27.0 48000.0]
 ['Sarah' 'Germany' 30.0 54000.0]
 ['Robert' 'Spain' 38.0 61000.0]
 ['Emma' 'Germany' 40.0 nan]
 ['Jennifer' 'France' 35.0 58000.0]
 ['Linda' 'Spain' nan 52000.0]
 ['Thomas' 'France' 48.0 79000.0]
 ['Ben' 'Germany' 50.0 83000.0]
 ['Scarlett' 'France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [54]:
# 마지막 열 index를 -1로 사용하면, 범용적으로 사용할 수 있음 (추천)
data = pd.read_csv('sample.csv').values
X = data[:,:-1]
y = data[:,-1]
print(X)
print(y)

[['James' 'France' 44.0 72000.0]
 ['Tim' 'Spain' 27.0 48000.0]
 ['Sarah' 'Germany' 30.0 54000.0]
 ['Robert' 'Spain' 38.0 61000.0]
 ['Emma' 'Germany' 40.0 nan]
 ['Jennifer' 'France' 35.0 58000.0]
 ['Linda' 'Spain' nan 52000.0]
 ['Thomas' 'France' 48.0 79000.0]
 ['Ben' 'Germany' 50.0 83000.0]
 ['Scarlett' 'France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [55]:
# y도 2d array로 로드해야할 경우도 있음
# 마지막 열도 범위로 지정 (-1: -> 마지막 열부터 끝까지 -> 마지막 열 하나만 의미함)
data = pd.read_csv('sample.csv').values
X = data[:,:-1]
y = data[:,-1:]
print(X)
print(y)

[['James' 'France' 44.0 72000.0]
 ['Tim' 'Spain' 27.0 48000.0]
 ['Sarah' 'Germany' 30.0 54000.0]
 ['Robert' 'Spain' 38.0 61000.0]
 ['Emma' 'Germany' 40.0 nan]
 ['Jennifer' 'France' 35.0 58000.0]
 ['Linda' 'Spain' nan 52000.0]
 ['Thomas' 'France' 48.0 79000.0]
 ['Ben' 'Germany' 50.0 83000.0]
 ['Scarlett' 'France' 37.0 67000.0]]
[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


In [57]:
# 참고
# DataFrame에서 X와 y를 분리한 후, ndarray로 변환
# csv를 로드할 때, values를 통해 ndarray로 저장하는 위 방법을 추천함
data = pd.read_csv('sample.csv')
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
print(X)
print(y)
# ndarray로 변환
X = X.values
y = y.values

       Name  Country   Age   Salary
0     James   France  44.0  72000.0
1       Tim    Spain  27.0  48000.0
2     Sarah  Germany  30.0  54000.0
3    Robert    Spain  38.0  61000.0
4      Emma  Germany  40.0      NaN
5  Jennifer   France  35.0  58000.0
6     Linda    Spain   NaN  52000.0
7    Thomas   France  48.0  79000.0
8       Ben  Germany  50.0  83000.0
9  Scarlett   France  37.0  67000.0
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


## 3. scikit-learn

In [58]:
import pandas as pd

In [65]:
dataset = pd.read_csv('classification_data/Data.csv').values
dataset

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [66]:
# X와 y로 분리
# X는 마지막 열을 제외한 모든 열, y는 마지막 열
X = dataset[:,:-1]
y = dataset[:,-1]
print(X)
print(y)
# shape은 코드 작성 중간에 자주 확인해보는 것을 추천
print(X.shape)
print(y.shape)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
(10, 3)
(10,)


In [69]:
# 문자열을 숫자로 변경
# 1. LabelEncoder: 특정 문자를 정수로 변환
# 문자를 0부터 시작하는 정수로 변경
# 단, 문자 값은 범주형 데이터로 간주함

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# LabelEncoder를 사용하겠다라고 선언, 이 LabelEncoder의 이름을 le로 하겠음
# X의 첫번째 열(Spain, France, Germany)을 정수로 변환하고자 함
le.fit(X[:,0])
# fit은 변환하기 전, 변환을 위한 사전 정보 취득 
# 몇 개의 데이터가 있는지, 어떠한 문자를 어떠한 정수로 변경할 건지 등
X_new = le.transform(X[:,0])
# 실제 변환 수행 (반드시 fit을 먼저 수행한 후, transform 수행)
print(X_new)

[0 2 1 2 1 0 2 0 1 0]


In [72]:
# 2. OneHotEncoder: 특정 문자를 0과 1이 조합된 2d array로 변환
# 단, 문자 값은 범주형 데이터로 간주함

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
# OneHotEncoder를 사용하겠다라고 선언, 이 OneHotEncoder의 이름을 ohe로 하겠음
# X의 첫번째 열(Spain, France, Germany)을 0과1로 조합된 2d array로 변환하고자 함
ohe.fit(X[:,:1])
# OneHotEncoder는 2D 형태로 반환되기 때문에, 입력도 2D가 되어야 함
# (1) X[:,:1]
# (2) X[:,0].reshape(-1,1)
# fit은 변환하기 전, 변환을 위한 사전 정보 취득 
# 몇 개의 데이터가 있는지, 어떠한 문자를 어떠한 값으로 변경할 건지 등
X_new = ohe.transform(X[:,:1]).toarray()
# 실제 변환 수행 (반드시 fit을 먼저 수행한 후, transform 수행)
# OneHotEncoder의 결과는 ndarray가 아니라 sparse_matrix
# 결과를 ndarray로 변환해야 함 (.toarray())
print(X_new)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [74]:
# 크기 변환
# 각 열 값의 범위가 크게 차이날 경우, 유사한 범위로 변환이 필요한 경우가 있음
# 1. StandardScaler
# 평균이 0이고 분산(표준편차)이 1인 데이터 형태로 변환
# 결과는 약 -3~+3 정도의 값으로 변환
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# 두번째, 세번째 열을 StandardScaler에 적용
sc.fit(X[:,1:])
# 변환(transform) 전, 반드시 fit을 수행해야 함
# fit은 입력된 데이터의 평균, 분산 등, 변환에 필요한 값을 구함 (변환을 수행하지는 않음)
X_sc = sc.transform(X[:,1:])
print('변환 전')
print(X[:,1:])
print('변환 후')
print(X_sc)

변환 전
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
변환 후
[[ 0.71993143  0.71101276]
 [-1.62367514 -1.36437583]
 [-1.21009751 -0.84552869]
 [-0.10722383 -0.24020701]
 [ 0.16849459         nan]
 [-0.52080146 -0.49963059]
 [        nan -1.01847774]
 [ 1.27136827  1.31633443]
 [ 1.54708669  1.66223253]
 [-0.24508304  0.27864014]]


In [76]:
# 2. MinMaxScaler
# 최대값과 최소값을 설정하여, 해당 범위의 값으로 변경
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
# 최대, 최소값을 설정하지 않는 경우, 디폴트로 최소값 0, 최대값 1
# 두번째, 세번째 열을 StandardScaler에 적용
mm.fit(X[:,1:])
# 변환(transform) 전, 반드시 fit을 수행해야 함
# fit은 입력된 데이터의 최대값, 최소값 등, 변환에 필요한 값을 구함 (변환을 수행하지는 않음)
X_mm = mm.transform(X[:,1:])
print('변환 전')
print(X[:,1:])
print('변환 후')
print(X_mm)

변환 전
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
변환 후
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739        nan]
 [0.34782609 0.28571429]
 [       nan 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]


In [118]:
# 학습데이터와 테스트데이터의 분리
from sklearn.model_selection import train_test_split
# 1. X와 y를 분리
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
# test_size는 전체 데이터에 대해 테스트 데이터의 비율
# 반드시 반환되는 데이터의 순서를 기억할 것
# random_state를 하나의 정수값으로 지정하면, 해당 값이 적용된 경우, 
# 항상 동일한 데이터를 반환함
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
print(X_train[0,:])
print(X_test[0,:])

(8, 3) (2, 3) (8,) (2,)
['France' 35.0 58000.0]
['Germany' 40.0 nan]


In [120]:
from sklearn.model_selection import train_test_split
# 2. dataset을 분리 후, X와 y로 나눔
dataset = pd.read_csv('Data.csv').values
data_train, data_test = train_test_split(dataset,test_size=0.2,random_state=2)

print(data_train.shape, data_test.shape)
print(data_train[0,:])
print(data_test[0,:])

X_train = data_train[:,:-1]
y_train = data_train[:,-1]
X_test = data_test[:,:-1]
y_test = data_test[:,-1]
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
print(X_train[0,:])
print(X_test[0,:])

(8, 4) (2, 4)
['France' 35.0 58000.0 'Yes']
['Germany' 40.0 nan 'Yes']
(8, 3) (2, 3) (8,) (2,)
['France' 35.0 58000.0]
['Germany' 40.0 nan]


- scaling(StandardScaler, MinMaxScaler)과 encoding(LabelEncoder, OneHotEncoder)은
- training data만 사용하여 fit을 적용하고
- test data는 training data를 이용하여 fit한 결과를 통해 transform만 수행

## 4. matplotlib

In [121]:
import matplotlib.pyplot as plt

- plt.plot(x,y) : 선차트 (x는 생략 가능, x 생략할 경우, 가로축 값은 index)
- plt.scatter(x,y) : 산점도